name: windows-test

on:
  push:
    branches: ["main"]
permissions:
  contents: write
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: echo
        shell: bash
        run: |
          echo 'windows bash'
          ls -ltr
          git config user.email "actions@github.com"
          git config user.name "actions"
          date >> date.txt
          git add .
          git commit -m 'add'
          git push

      - name: Create a release pull request
        uses: actions/create-release@v1
        id: create_release
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            Changes in this Release
            - First Change
            - Second Change
          draft: false
          prerelease: false
